---
name: Release digitalocean-exporter binary

"on":
  push:
    branches:
      - main
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish as a GitHub release'
        required: false
        type: boolean
        default: false
      tag:
        description: 'Git Tag to build and publish'
        required: false
        type: string
        default: ''
      archs:
        description: 'Architecture to build and publish'
        required: false
        type: choice
        options:
          - [amd64, arm64]
          - [amd64]
          - [arm64]

jobs:
  #
  # Linux
  #
  release-linux:
    name: Release digitalocean-exporter on Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.archs || '["amd64", "arm64"]') }}
    env:
      GOOS: linux
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: 0
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: 'digitalocean-exporter'
          ref: ${{ inputs.tag }}

      - name: Sanity check
        working-directory: 'digitalocean-exporter'
        run: |
          git rev-parse --verify HEAD
          git status

      - name: Build binary
        working-directory: 'digitalocean-exporter'
        run: go build -ldflags '-extldflags "-static"' -o ../build/digitalocean-exporter .

      - name: Build binary with version override
        if: ${{ inputs.tag || startsWith(github.ref, 'refs/tags/') }}
        working-directory: 'digitalocean-exporter'
        run: go build -ldflags "-extldflags '-static' -X main.Version=${{ inputs.tag || github.ref_name }} -X main.Revision=$(git rev-parse --short HEAD)" -o ../build/digitalocean-exporter .

      - name: Check version
        if: ${{ env.GOARCH == 'amd64' }}
        working-directory: build
        run: ./digitalocean-exporter --version

      - name: Bundle binary in archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: build
          filename: digitalocean-exporter-${{ env.GOOS }}-${{ env.GOARCH }}.zip

      - name: Release
        if: ${{ inputs.publish || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: build/*.zip
          name: ${{ inputs.tag || github.ref_name }}
          tag_name: ${{ inputs.tag || github.ref_name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
